/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepoRouteImport } from './routes/repo'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const RepoRoute = RepoRouteImport.update({
  id: '/repo',
  path: '/repo',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/pitch': typeof PitchRoute
  '/repo': typeof RepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/pitch': typeof PitchRoute
  '/repo': typeof RepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/demo': typeof DemoRoute
  '/pitch': typeof PitchRoute
  '/repo': typeof RepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/architecture' | '/demo' | '/pitch' | '/repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/architecture' | '/demo' | '/pitch' | '/repo'
  id: '__root__' | '/' | '/architecture' | '/demo' | '/pitch' | '/repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  DemoRoute: typeof DemoRoute
  PitchRoute: typeof PitchRoute
  RepoRoute: typeof RepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repo': {
      id: '/repo'
      path: '/repo'
      fullPath: '/repo'
      preLoaderRoute: typeof RepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  DemoRoute: DemoRoute,
  PitchRoute: PitchRoute,
  RepoRoute: RepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
